name: Setup & test

on: [ push, pull_request ]

jobs:
  tests:
    name: Composer P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php: [ '8.4', '8.5' ]
        laravel: [ 12.*, 11.* ]
        include:
          - laravel: 12.*
            php: 8.4
          - laravel: 12.*
            php: 8.5
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          composer install --no-interaction --no-progress --no-suggest

      - name: Run tests
        run: |
          composer validate --strict
